### ISSUE TITLE
Hi, how to get user profile data like : username, email, phone number ?

### ISSUE THREAD

**Issue by francelwebdev** [syetalabs/vue3-google-signin#11]
Hi, I tested this library and I get credential, but I don't know why I don't get user profile data like : username, email, phone number ?

**Comment by kasvith** [comment]
Hi, you need to decode and verify the token received from google servers to obtain that. Its not a part of this library. You may need to follow this guide after getting credential responses.

Guides to Follow: 
https://developers.google.com/identity/gsi/web/guides/handle-credential-responses-js-functions
https://stackoverflow.com/questions/68524360/how-can-i-decode-a-google-oauth-2-0-jwt-credential-token
