### ISSUE TITLE
Usage with Google API's and firebase

### ISSUE THREAD

**Issue by kpoman** [syetalabs/vue3-google-signin#20]
Hello,
Is there an example of using, say, calendar api with this lib ? And also, something that would use Firebase Google Auth together with this one ? How should they behave or interact ?
Thank you

**Comment by kasvith** [comment]
Hi, to use calendar API add the relevant scope with a custom button.

Once you obtains the token, use it with firebase for IDP https://firebase.google.com/docs/auth/web/google-signin#expandable-2
