### ISSUE TITLE
Vite build fails when building vue3-google-signin package in my app

### ISSUE THREAD

**Issue by philippedasilva-orizone** [syetalabs/vue3-google-signin#31]
**Describe the bug**
My build fails when trying to import from vue package in the dist/index.es.js on line 1

**To Reproduce**
I admit I didn't try to reproduce it on another project but on mine it would consist on

1. clone @antfu/vitesse template repository
2. install vue3-google-signin package latest version (should do the same with previous too)
3. implement GoogleSignIn button in an existing page
4. build the project
5. Note the build error in the console output

**Expected behaviour**
Should build :)

**Screenshots**
![Screenshot 2022-11-02 at 00 24 45](https://user-images.githubusercontent.com/77384971/199360842-909dd98a-4531-4b4a-86b3-4fa37e3d5b03.png)

**Additional context**
I override my local install in `node_modules/vue3-google-signin`simply adding the `"type": "module"` line in `package.json`and the build succeed.

**Comment by philippedasilva-orizone** [comment]
As mentioned, @kasvith it should be a pretty easy one to solve...
Just add the type: "package" to the package.json file :)

**Comment by kasvith** [comment]
This plugin provides ESM and CJS both versions, need to check with vite-ssg

Would you mind sharing a minimum reproducible with stackblitz.io

**Comment by kasvith** [comment]
Hi @philippedasilva-orizone thanks for the report, will fix this soon

**Comment by kasvith** [comment]
Should be fixed on v1.2.1

**Comment by kasvith** [comment]
@philippedasilva-orizone how ever I found a bug in prod mode with vite-ssg, it seems not correctly mounting the components.

To make sure I used Nuxt3 and tried to do a prod build with the same params, Nuxt version worked without any issues.
So please be cautious.

**Comment by philippedasilva-orizone** [comment]
Did you place a bug in their issues list for me to look at? If not, could you quickly explain the actual effect because, on my end, it's working fine

**Comment by kasvith** [comment]
Did you tried a prod build and serving it with `preview`

**Comment by philippe-dasilva** [comment]
Yes I did
