### ISSUE TITLE
Missing required parameter client_id when using useTokenClient on vite

### ISSUE THREAD

**Issue by ArthurWize** [syetalabs/vue3-google-signin#33]
I'm trying to use useTokenClient on a vite and vue 3 project to have custom buttons. But the project show this error on console.
<img width="873" alt="Captura de pantalla 2022-11-18 a la(s) 17 32 40" src="https://user-images.githubusercontent.com/113947057/202820254-abf11da6-85c7-47b0-bf16-3f4755ef9280.png">

**Comment by kasvith** [comment]
@ArthurWize is this resolved?

**Comment by simonmaass** [comment]
I am getting the same error with nuxt 3... @ArthurWize did u ever resolve this?

**Comment by ricardo-alan** [comment]
> I am getting the same error with nuxt 3... @ArthurWize did u ever resolve this?

I first initialized the plugin in `plugins/auth.server.ts` but then I changed the file name to `plugins/auth.ts`and the problem was solved. 

This is my code:

```
import GoogleSignInPlugin from 'vue3-google-signin'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(GoogleSignInPlugin, {
    clientId: 'my-client-id'
  });
})
```
