### ISSUE TITLE
Invalid access access token format

### ISSUE THREAD

**Issue by musqdp** [syetalabs/vue3-google-signin#41]
**Describe the bug**
Success callback returns incorrect JWT formated access token, somethink like `ya29.a0A` . Valid JWT token consists from header,payload and signature `xxxxx.yyyyy.zzzzz`

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page with google oauth
2. Click on button to sign
3. See at console response with access_token

**Comment by kasvith** [comment]
This is what i getting from following page https://vue3-google-signin.syetalabs.io/guide/google-signin-button.html
![image](https://user-images.githubusercontent.com/13379595/217435556-dbe02101-ac51-454f-a6df-7bf547ec9039.png)

If you are talking about custom buttons with OAuth flow, you must acquire the tokens from your backend using following method https://vue3-google-signin.syetalabs.io/guide/creating-custom-buttons.html#verify-code-on-the-backend

**Comment by musqdp** [comment]
Is it possible to retrieve JWT token with customized button?

**Comment by kasvith** [comment]
You need a server for that

**Comment by kasvith** [comment]
@musqdp unfortunately its how google oauth2 flow works

Its not a problem with this library. You can use a serverless platform like Supabase to tackle this

**Comment by iUnknownWs** [comment]
@kasvith  There's no way to return credential using a button with custom styles?

I'm using this to verify the token and it says Wrong number of segments in token with customs buttons

```
from google.oauth2 import id_token
from google.auth.transport import requests

try:
    # Specify the CLIENT_ID of the app that accesses the backend:
    idinfo = id_token.verify_oauth2_token(token, requests.Request(), CLIENT_ID)

    # Or, if multiple clients access the backend server:
    # idinfo = id_token.verify_oauth2_token(token, requests.Request())
    # if idinfo['aud'] not in [CLIENT_ID_1, CLIENT_ID_2, CLIENT_ID_3]:
    #     raise ValueError('Could not verify audience.')

    # If the request specified a Google Workspace domain
    # if idinfo['hd'] != DOMAIN_NAME:
    #     raise ValueError('Wrong domain name.')

    # ID token is valid. Get the user's Google Account ID from the decoded token.
    userid = idinfo['sub']
except ValueError:
    # Invalid token
    pass
```
